# Generated by Django 5.0.3 on 2024-03-27 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='group',
        ),
        migrations.RemoveField(
            model_name='job',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='job',
            name='playbook',
        ),
        migrations.RemoveField(
            model_name='jobrunned',
            name='job',
        ),
        migrations.RemoveField(
            model_name='jobrunned',
            name='status',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.DeleteModel(
            name='Playbook',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='JobRunned',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
