# Generated by Django 5.0.3 on 2024-05-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_jobrunned_datetime_job_description_job_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='name',
            field=models.CharField(default=1, max_length=14),
            preserve_default=False,
        ),
    ]
