# Generated by Django 5.0.3 on 2024-06-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_job_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrunned',
            name='username',
            field=models.CharField(max_length=8),
        ),
    ]
